//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReklamotvTeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firmalar
    {
        public Firmalar()
        {
            this.ReserveUrunler = new HashSet<ReserveUrunler>();
            this.SatilanUrunler = new HashSet<SatilanUrunler>();
            this.SikayetUrunler = new HashSet<SikayetUrunler>();
            this.StoktakiUrunler = new HashSet<StoktakiUrunler>();
        }
    
        public int FirmaId { get; set; }
        public string FirmaAdi { get; set; }
        public string FirmaAdresi { get; set; }
        public string FirmaTelNo { get; set; }
        public Nullable<int> FirmaAlınanSatilan { get; set; }
    
        public virtual ICollection<ReserveUrunler> ReserveUrunler { get; set; }
        public virtual ICollection<SatilanUrunler> SatilanUrunler { get; set; }
        public virtual ICollection<SikayetUrunler> SikayetUrunler { get; set; }
        public virtual ICollection<StoktakiUrunler> StoktakiUrunler { get; set; }
    }
}
