//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReklamotvTeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenelUrunler
    {
        public GenelUrunler()
        {
            this.SatilanUrunler = new HashSet<SatilanUrunler>();
            this.StoktakiUrunler = new HashSet<StoktakiUrunler>();
        }
    
        public int Urun_id { get; set; }
        public string Urun_adi { get; set; }
        public string Urun_kodu { get; set; }
        public Nullable<System.DateTime> Urun_Ol_Tarih { get; set; }
    
        public virtual ICollection<SatilanUrunler> SatilanUrunler { get; set; }
        public virtual ICollection<StoktakiUrunler> StoktakiUrunler { get; set; }
    }
}
