//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReklamotvTeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelTable
    {
        public PersonelTable()
        {
            this.SatilanUrunler = new HashSet<SatilanUrunler>();
        }
    
        public int Personel_id { get; set; }
        public string Personel_adi { get; set; }
        public string Personel_soyadi { get; set; }
        public string Personel_departman { get; set; }
    
        public virtual ICollection<SatilanUrunler> SatilanUrunler { get; set; }
    }
}
