//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReklamotvTeknikServis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReklamoStokTakipEntities : DbContext
    {
        public ReklamoStokTakipEntities()
            : base("name=ReklamoStokTakipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GenelUrunler> GenelUrunler { get; set; }
        public virtual DbSet<SatilanUrunler> SatilanUrunler { get; set; }
        public virtual DbSet<StoktakiUrunler> StoktakiUrunler { get; set; }
        public virtual DbSet<PersonelTable> PersonelTable { get; set; }
        public virtual DbSet<BirlestirilenUrun> BirlestirilenUrun { get; set; }
        public virtual DbSet<Firmalar> Firmalar { get; set; }
        public virtual DbSet<ReserveUrunler> ReserveUrunler { get; set; }
        public virtual DbSet<SikayetTur> SikayetTur { get; set; }
        public virtual DbSet<SikayetUrunler> SikayetUrunler { get; set; }
        public virtual DbSet<BirlestirilenParcalar> BirlestirilenParcalar { get; set; }
    }
}
