//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReklamotvTeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatilanUrunler
    {
        public SatilanUrunler()
        {
            this.SikayetUrunler = new HashSet<SikayetUrunler>();
        }
    
        public int SatilanUrun_id { get; set; }
        public string SatilanUrun_adi { get; set; }
        public Nullable<int> SatanPersonel { get; set; }
        public Nullable<System.DateTime> UrununSatilisTarihi { get; set; }
        public Nullable<decimal> UrunSatisFiyati { get; set; }
        public int UrunTur_id { get; set; }
        public Nullable<int> UrunStok_id { get; set; }
        public Nullable<double> UrunToplamKar { get; set; }
        public Nullable<double> SatilanUrunAdet { get; set; }
        public Nullable<int> FirmaId { get; set; }
    
        public virtual GenelUrunler GenelUrunler { get; set; }
        public virtual StoktakiUrunler StoktakiUrunler { get; set; }
        public virtual PersonelTable PersonelTable { get; set; }
        public virtual Firmalar Firmalar { get; set; }
        public virtual ICollection<SikayetUrunler> SikayetUrunler { get; set; }
    }
}
