//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReklamotvTeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class SikayetUrunler
    {
        public int SikayetId { get; set; }
        public Nullable<int> SatilanUrunId { get; set; }
        public Nullable<int> UrunStokId { get; set; }
        public Nullable<int> SikayetTuruId { get; set; }
        public Nullable<int> FirmaId { get; set; }
        public Nullable<double> UrunAdet { get; set; }
        public Nullable<System.DateTime> SikayetTarihi { get; set; }
    
        public virtual Firmalar Firmalar { get; set; }
        public virtual SatilanUrunler SatilanUrunler { get; set; }
        public virtual SikayetTur SikayetTur { get; set; }
        public virtual StoktakiUrunler StoktakiUrunler { get; set; }
    }
}
