//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReklamotvTeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class SikayetTur
    {
        public SikayetTur()
        {
            this.SikayetUrunler = new HashSet<SikayetUrunler>();
        }
    
        public int SikayetTurId { get; set; }
        public string SikayetAciklama { get; set; }
    
        public virtual ICollection<SikayetUrunler> SikayetUrunler { get; set; }
    }
}
