//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReklamotvTeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoktakiUrunler
    {
        public StoktakiUrunler()
        {
            this.SatilanUrunler = new HashSet<SatilanUrunler>();
            this.BirlestirilenUrun = new HashSet<BirlestirilenUrun>();
            this.ReserveUrunler = new HashSet<ReserveUrunler>();
            this.SikayetUrunler = new HashSet<SikayetUrunler>();
            this.BirlestirilenParcalar = new HashSet<BirlestirilenParcalar>();
        }
    
        public int UrunStok_id { get; set; }
        public Nullable<decimal> UrunAlisFiyati { get; set; }
        public Nullable<int> UrunTur_id { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<double> UrunAdet { get; set; }
        public Nullable<System.DateTime> UrunGirisTarihi { get; set; }
        public Nullable<int> FirmaId { get; set; }
    
        public virtual GenelUrunler GenelUrunler { get; set; }
        public virtual ICollection<SatilanUrunler> SatilanUrunler { get; set; }
        public virtual ICollection<BirlestirilenUrun> BirlestirilenUrun { get; set; }
        public virtual Firmalar Firmalar { get; set; }
        public virtual ICollection<ReserveUrunler> ReserveUrunler { get; set; }
        public virtual ICollection<SikayetUrunler> SikayetUrunler { get; set; }
        public virtual ICollection<BirlestirilenParcalar> BirlestirilenParcalar { get; set; }
    }
}
